### ISSUE TITLE
SyntaxError: invalid regular expression flag s in scoresaber_lib.js:73:57

### ISSUE THREAD

**Issue by themoonisacheese** [flyinggiants/ScoreSaber-Rank-Panel#2]
as per the doc, s is a valid flag, but it doesn't work on firefox 68.3.0 esr.
you could try to pass it to a regex constructor as a separate argument.

maybe related: https://bugzilla.mozilla.org/show_bug.cgi?id=1579867

**Comment by themoonisacheese** [comment]
Apparently firefox just straight up doesn't implement dotAll.
I have the same issue using edge, but I mean, edge.

**Comment by LucaVazz** [comment]
additional tracking: https://sentry.io/organizations/twitch-lv/issues/1096736262/?project=1482624

additional FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1361856

**Comment by LucaVazz** [comment]
Hey @themoonisacheese,

thank you for your report and the bugzilla link, that helped me investigate the problem.


From my side this issue seems to be fixed (tested in Firefox 71.0, Firefox Developer Edition 72.0b7, Firefox ESR 68.3.0). 

The change will be published after the usual review from Twitch's side, so in about 3-5 days after I've got feedback on #1.

**Comment by themoonisacheese** [comment]
absolutely fantastic. feel free to close at your leisure.

**Comment by LucaVazz** [comment]
The new version was released yesterday.
Marking the issue as closed, please comment if it re-appears on your side.
